### ISSUE TITLE
Readiness checklist

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-sessions#18]
* [ ] Design Signoff - Alex and YK
* [x]  Development - Alex
* [x]  Peer Review - Alex and his team
* [x]  Content Review - Eveline
* [x]  SME Review - Alex and his team
* [x]  User Review - Rachel 
* [ ]  Signoff Review - YK

**Comment by yeekangc** [comment]
I don't believe this guide is ready.  Not all the items prior to final sign-off are done and there are still issues to consider.

@evelinec @gkwan-ibm

**Comment by evelinec** [comment]
No longer needed. Closed.
